### ISSUE TITLE
Add Content for Code-Conventions.md

### ISSUE THREAD

**Issue by wenshilanR** [JoyfulTechLauncher/docs#10]
**Document Name:**
Code-Conventions.md

**Task:**
This document should outline the coding conventions and guidelines that developers should follow when writing code for the project. It serves as a reference for consistent coding practices, which can include naming conventions, code formatting standards, indentation rules, and other stylistic choices.

**Comment by Qingyang0818** [comment]
We have already uploaded the detail instruction for code conventions.
[https://github.com/JoyfulTechLauncher/docs/blob/dev/Code/Code-Conventions.md](url)
