### ISSUE TITLE
Add Content for Code-Style.md

### ISSUE THREAD

**Issue by wenshilanR** [JoyfulTechLauncher/docs#12]
**Document Name:**
Code-Style.md

**Task:**
Code Style documentation should go beyond conventions and delve into the best practices, design patterns, and architectural choices used in the project.

**Comment by Qingyang0818** [comment]
We have already uploaded the full structure of our project in the docs repo. [https://github.com/JoyfulTechLauncher/docs/blob/dev/Code/Code-Structure.md](url)
